"""Chart geometry, generated by the engine rather than by the browser.

The brief (SS26, SS61) requires that psychrometric equations do not live in
frontend code and are not duplicated anywhere. A psychrometric chart is mostly
*curves* -- the saturation line, the relative-humidity family, isenthalps,
wet-bulb lines, constant-volume lines -- and those curves are evaluations of
the same relations as the state itself. So the backend computes them and the
frontend draws the polylines it is given.

Two consequences worth stating:

* the chart cannot disagree with the numbers beside it, because they come from
  one evaluation path;
* changing the total pressure changes the chart, correctly and automatically,
  which a browser-side chart drawn for a nominal sea-level atmosphere would
  not do.

Every curve is returned in base units (degC, kg/kg_da, kJ/kg_da). The API layer
converts to display units once, at the boundary.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any

from . import psychrometrics as psy
from .constants import STANDARD_PRESSURE_PA
from .mollier import isotherm_ordinate, mollier_ordinate

__all__ = ["Curve", "ChartGeometry", "build_psychrometric_chart", "build_mollier_chart"]


@dataclass(frozen=True, slots=True)
class Curve:
    """A labelled polyline in chart coordinates.

    ``points`` are ``(abscissa, ordinate)`` pairs in the chart's own
    coordinates; which physical quantity that is depends on ``family`` and on
    which chart built the curve.
    """

    family: str
    label: str
    value: float
    points: list[tuple[float, float]]

    def to_dict(self) -> dict[str, Any]:
        return {
            "family": self.family,
            "label": self.label,
            "value": self.value,
            "points": [[round(a, 5), round(b, 7)] for a, b in self.points],
        }


@dataclass(frozen=True, slots=True)
class ChartGeometry:
    """Everything needed to draw one chart, minus the styling."""

    mode: str
    pressure: float
    x_axis: dict[str, Any]
    y_axis: dict[str, Any]
    curves: list[Curve] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        return {
            "mode": self.mode,
            "pressure_kpa": round(self.pressure / 1000.0, 5),
            "x_axis": self.x_axis,
            "y_axis": self.y_axis,
            "curves": [curve.to_dict() for curve in self.curves],
        }


#: Default relative-humidity family. 100 % is drawn separately as the
#: saturation boundary, which is the curve everything else is clipped to.
DEFAULT_RH_LINES: tuple[float, ...] = (10, 20, 30, 40, 50, 60, 70, 80, 90)


def _saturation_points(
    t_min: float, t_max: float, pressure: float, steps: int
) -> list[tuple[float, float]]:
    """Points on the 100 % RH boundary, ``(t, W_s(t))``."""
    points: list[tuple[float, float]] = []
    for index in range(steps + 1):
        t = t_min + (t_max - t_min) * index / steps
        try:
            points.append((t, psy.saturation_humidity_ratio(t, pressure)))
        except psy.PsychrometricRangeError:
            continue
    return points


def _target_zone_points(
    target: tuple[float, float, float, float],
    pressure: float,
    w_max: float,
    steps: int = 40,
) -> list[tuple[float, float]]:
    """A closed polygon, in ``(t, W)``, bounding a crop's target band.

    ``target`` is ``(temperature_min, temperature_max, humidity_min,
    humidity_max)`` -- the same four numbers a crop record stores. The
    boundary is not a rectangle: at fixed relative humidity, humidity ratio
    rises with temperature, so the top and bottom edges are the RH curves
    already drawn elsewhere on the chart, just clipped to this crop's band and
    its temperature range. Reusing the exact relation that draws the RH family
    is what keeps this zone honest rather than a decorative rectangle.
    """
    t_lo, t_hi, rh_lo, rh_hi = target
    if t_hi <= t_lo:
        return []

    top: list[tuple[float, float]] = []
    for index in range(steps + 1):
        t = t_lo + (t_hi - t_lo) * index / steps
        try:
            w = psy.humidity_ratio_from_relative_humidity(t, rh_hi, pressure)
        except psy.PsychrometricRangeError:
            continue
        top.append((t, min(w, w_max)))

    bottom: list[tuple[float, float]] = []
    for index in range(steps + 1):
        t = t_hi - (t_hi - t_lo) * index / steps
        try:
            w = psy.humidity_ratio_from_relative_humidity(t, rh_lo, pressure)
        except psy.PsychrometricRangeError:
            continue
        bottom.append((t, min(w, w_max)))

    if not top or not bottom:
        return []
    return [*top, *bottom, top[0]]


def build_psychrometric_chart(
    t_min: float = 0.0,
    t_max: float = 50.0,
    w_max: float = 0.030,
    pressure: float = STANDARD_PRESSURE_PA,
    rh_lines: tuple[float, ...] = DEFAULT_RH_LINES,
    enthalpy_step: float = 10.0,
    wet_bulb_step: float = 5.0,
    volume_step: float = 0.02,
    steps: int = 120,
    target: tuple[float, float, float, float] | None = None,
) -> ChartGeometry:
    """Geometry for the ASHRAE-convention chart: ``t`` against ``W``.

    :param t_min, t_max: dry-bulb axis range [degC]
    :param w_max: humidity-ratio axis ceiling [kg/kg_da]
    :param pressure: total pressure [Pa] -- the curves genuinely depend on it
    :param rh_lines: relative-humidity family to draw [%]
    :param enthalpy_step: spacing of the isenthalp family [kJ/kg_da]
    :param wet_bulb_step: spacing of the wet-bulb family [degC]
    :param volume_step: spacing of the constant-volume family [m3/kg_da]
    :param steps: points per curve; 120 is visually smooth at any sane zoom
    :param target: a crop's ``(temperature_min, temperature_max,
        humidity_min, humidity_max)``, drawn as a shaded target zone
    """
    psy.validate_pressure(pressure)
    curves: list[Curve] = []

    # -- target zone, drawn first so every other curve sits above it -----
    if target is not None:
        zone = _target_zone_points(target, pressure, w_max)
        if zone:
            curves.append(Curve(family="target_zone", label="Target", value=0.0, points=zone))

    # -- saturation boundary (100 % RH) ---------------------------------
    curves.append(
        Curve(
            family="saturation",
            label="100 % RH",
            value=100.0,
            points=[(t, w) for t, w in _saturation_points(t_min, t_max, pressure, steps)
                    if w <= w_max * 1.5],
        )
    )

    # -- relative-humidity family ---------------------------------------
    for rh in rh_lines:
        points: list[tuple[float, float]] = []
        for index in range(steps + 1):
            t = t_min + (t_max - t_min) * index / steps
            try:
                w = psy.humidity_ratio_from_relative_humidity(t, rh, pressure)
            except psy.PsychrometricRangeError:
                continue
            if w > w_max:
                break
            points.append((t, w))
        if len(points) > 1:
            curves.append(
                Curve(family="relative_humidity", label=f"{rh:g} %", value=rh, points=points)
            )

    # -- isenthalps ------------------------------------------------------
    # Bounded by the enthalpy of the coldest dry corner and the hottest
    # saturated corner, so the family spans exactly the drawn region.
    h_low = psy.enthalpy(t_min, 0.0)
    h_high = psy.enthalpy(t_max, min(w_max, psy.saturation_humidity_ratio(t_max, pressure)))
    h_start = enthalpy_step * (int(h_low // enthalpy_step))
    h_value = h_start
    while h_value <= h_high + enthalpy_step:
        points = []
        for index in range(steps + 1):
            t = t_min + (t_max - t_min) * index / steps
            w = psy.humidity_ratio_from_enthalpy(t, h_value)
            if w < 0.0 or w > w_max:
                continue
            try:
                if w > psy.saturation_humidity_ratio(t, pressure) * 1.001:
                    continue
            except psy.PsychrometricRangeError:
                continue
            points.append((t, w))
        if len(points) > 1:
            curves.append(
                Curve(
                    family="enthalpy",
                    label=f"{h_value:g} kJ/kg",
                    value=h_value,
                    points=points,
                )
            )
        h_value += enthalpy_step

    # -- wet-bulb family --------------------------------------------------
    # Each line runs from its own saturation point (where t = t_wb) rightwards
    # to the dry edge of the plot; it is drawn from Eq. (33)/(34) directly, so
    # it is a true thermodynamic wet-bulb line and not the isenthalp
    # approximation that many hand-drawn charts substitute for it.
    t_wb = wet_bulb_step * int(t_min // wet_bulb_step)
    while t_wb <= t_max:
        if t_wb >= t_min:
            points = []
            for index in range(steps + 1):
                t = t_wb + (t_max - t_wb) * index / steps
                try:
                    w = psy.humidity_ratio_from_wet_bulb(t, t_wb, pressure)
                except psy.PsychrometricRangeError:
                    continue
                if w <= 0.0 or w > w_max:
                    continue
                points.append((t, w))
            if len(points) > 1:
                curves.append(
                    Curve(
                        family="wet_bulb",
                        label=f"{t_wb:g} °C wb",
                        value=t_wb,
                        points=points,
                    )
                )
        t_wb += wet_bulb_step

    # -- constant specific volume ----------------------------------------
    v_low = psy.specific_volume(t_min, 0.0, pressure)
    v_high = psy.specific_volume(t_max, w_max, pressure)
    v_value = volume_step * (int(v_low / volume_step) + 1)
    while v_value <= v_high:
        points = []
        for index in range(steps + 1):
            t = t_min + (t_max - t_min) * index / steps
            # Eq. (26) solved for W at fixed v.
            w = (v_value * pressure / (287.042 * (t + 273.15)) - 1.0) / 1.607858
            if w < 0.0 or w > w_max:
                continue
            try:
                if w > psy.saturation_humidity_ratio(t, pressure) * 1.001:
                    continue
            except psy.PsychrometricRangeError:
                continue
            points.append((t, w))
        if len(points) > 1:
            curves.append(
                Curve(
                    family="specific_volume",
                    label=f"{v_value:.2f} m³/kg",
                    value=v_value,
                    points=points,
                )
            )
        v_value += volume_step

    return ChartGeometry(
        mode="psychrometric",
        pressure=pressure,
        x_axis={
            "quantity": "dry_bulb_temperature",
            "unit": "°C",
            "min": t_min,
            "max": t_max,
        },
        y_axis={
            "quantity": "humidity_ratio",
            "unit": "g/kg dry air",
            "min": 0.0,
            "max": w_max * 1000.0,
            "scale_to_base": 0.001,
        },
        curves=curves,
    )


def build_mollier_chart(
    t_min: float = 0.0,
    t_max: float = 50.0,
    w_max: float = 0.030,
    pressure: float = STANDARD_PRESSURE_PA,
    rh_lines: tuple[float, ...] = DEFAULT_RH_LINES,
    isotherm_step: float = 5.0,
    enthalpy_step: float = 10.0,
    steps: int = 120,
    target: tuple[float, float, float, float] | None = None,
) -> ChartGeometry:
    """Geometry for the Mollier h-x chart: ``x = W`` against ``h - 2501 W``.

    Built from the same relations as :func:`build_psychrometric_chart` and then
    re-projected, so the two charts cannot drift apart. Isotherms are explicit
    here because on an h-x chart they are the curves that carry the temperature
    information the abscissa no longer does.

    :param target: a crop's ``(temperature_min, temperature_max,
        humidity_min, humidity_max)``, drawn as a shaded target zone
    """
    psy.validate_pressure(pressure)
    curves: list[Curve] = []

    # -- target zone, drawn first so every other curve sits above it -----
    if target is not None:
        zone_tw = _target_zone_points(target, pressure, w_max)
        zone = [
            (w * 1000.0, mollier_ordinate(psy.enthalpy(t, w), w))
            for t, w in zone_tw
        ]
        if zone:
            curves.append(Curve(family="target_zone", label="Target", value=0.0, points=zone))

    # -- saturation boundary ---------------------------------------------
    saturation = [
        (w * 1000.0, mollier_ordinate(psy.enthalpy(t, w), w))
        for t, w in _saturation_points(t_min, t_max, pressure, steps)
        if w <= w_max * 1.5
    ]
    curves.append(
        Curve(family="saturation", label="100 % RH", value=100.0, points=saturation)
    )

    # -- relative-humidity family -----------------------------------------
    for rh in rh_lines:
        points = []
        for index in range(steps + 1):
            t = t_min + (t_max - t_min) * index / steps
            try:
                w = psy.humidity_ratio_from_relative_humidity(t, rh, pressure)
            except psy.PsychrometricRangeError:
                continue
            if w > w_max:
                break
            points.append((w * 1000.0, mollier_ordinate(psy.enthalpy(t, w), w)))
        if len(points) > 1:
            curves.append(
                Curve(family="relative_humidity", label=f"{rh:g} %", value=rh, points=points)
            )

    # -- isotherms ---------------------------------------------------------
    t_value = isotherm_step * int(t_min // isotherm_step)
    while t_value <= t_max:
        if t_value >= t_min:
            points = []
            for index in range(steps + 1):
                w = w_max * index / steps
                try:
                    if w > psy.saturation_humidity_ratio(t_value, pressure) * 1.001:
                        break
                except psy.PsychrometricRangeError:
                    break
                points.append((w * 1000.0, isotherm_ordinate(t_value, w)))
            if len(points) > 1:
                curves.append(
                    Curve(
                        family="isotherm",
                        label=f"{t_value:g} °C",
                        value=t_value,
                        points=points,
                    )
                )
        t_value += isotherm_step

    # -- isenthalps --------------------------------------------------------
    # On the skewed ordinate an isenthalp is the straight line
    # ``y = h - 2501 W``; two endpoints would suffice, but the curve is
    # clipped against saturation so it is sampled like the others.
    h_low = psy.enthalpy(t_min, 0.0)
    h_high = psy.enthalpy(t_max, w_max)
    h_value = enthalpy_step * int(h_low // enthalpy_step)
    while h_value <= h_high + enthalpy_step:
        points = []
        for index in range(steps + 1):
            w = w_max * index / steps
            t = psy.temperature_from_enthalpy(h_value, w)
            if not (t_min - 5.0 <= t <= t_max + 5.0):
                continue
            points.append((w * 1000.0, mollier_ordinate(h_value, w)))
        if len(points) > 1:
            curves.append(
                Curve(
                    family="enthalpy",
                    label=f"{h_value:g} kJ/kg",
                    value=h_value,
                    points=points,
                )
            )
        h_value += enthalpy_step

    return ChartGeometry(
        mode="mollier",
        pressure=pressure,
        x_axis={
            "quantity": "humidity_ratio",
            "unit": "g/kg dry air",
            "min": 0.0,
            "max": w_max * 1000.0,
        },
        y_axis={
            "quantity": "mollier_ordinate",
            "unit": "kJ/kg dry air (h − 2501·W)",
            "min": min((p[1] for c in curves for p in c.points), default=0.0),
            "max": max((p[1] for c in curves for p in c.points), default=100.0),
        },
        curves=curves,
    )
